version: "3.9"

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8081:8080"
