name: Auto Minify

on:
  push:
    branches:
      - master
      - quanti-function

jobs:
  auto-minify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: JulesWhatson/auto-minify@v1.0
        with:
          directory: 'dist'
          output: 'minified'

      # Auto commits minified files to the repository
      - name: Auto committing minified files
        uses: JulesWhatson/git-auto-commit-action@v1.0
        with:
          repository: 'minified'
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}