name: Auto Minify

on:
  push:
    branches:
      - main

jobs:
  auto-minify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Minify-JS Action
        uses: jossydevers/minify-js@v1.0.0
        with:
          directory: 'static'
          output: 'dist'

      # Auto commits minified files to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minify-JS : Commit Pipeline'
          branch: ${{ github.ref }}